{% set name = "yarp-device-realsense2" %}
{% set version = "0.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/robotology/yarp-device-realsense2/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bf0b1a83aba5615191e67b9592a79e47121869d5d9b79437e72f46830c24ab97

build:
  number: 1
  # librealsense conda package is not available on Windows
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - librealsense
    - libyarp

test:
  commands:
    # Note: the devices are added in CMake add_library(... MODULE),
    # so also on macos they have the .so extension, instead of the .dylib
    # extension that add_library(... SHARED) typically have
    - test -f ${PREFIX}/lib/yarp/yarp_realsense2.so  # [not win]
    - test -f ${PREFIX}/lib/yarp/yarp_realsense2withIMU.so  # [not win]

about:
  home: https://github.com/robotology/yarp-device-realsense2
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: realsense2 device for YARP.

extra:
  feedstock-name: yarp-device-realsense2
  recipe-maintainers:
    - traversaro
