{% set name = "yarp-device-realsense2" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/robotology/yarp-device-realsense2/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 63a92c0d7a7dd820e237bd628da9bdb82f352c8a65a8292edd2c1e6ce6e1ab01

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - librealsense
    - libyarp

test:
  commands:
    # Note: the devices are added in CMake add_library(... MODULE),
    # so also on macos they have the .so extension, instead of the .dylib
    # extension that add_library(... SHARED) typically have
    - test -f ${PREFIX}/lib/yarp/yarp_realsense2.so  # [not win]
    - test -f ${PREFIX}/lib/yarp/yarp_realsense2withIMU.so  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\yarp\\yarp_realsense2.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\yarp\\yarp_realsense2withIMU.dll exit 1  # [win]

about:
  home: https://github.com/robotology/yarp-device-realsense2
  license: BSD-3-Clause
  license_file:
    - LICENSE
  summary: realsense2 device for YARP.

extra:
  feedstock-name: yarp-device-realsense2
  recipe-maintainers:
    - Nicogene
    - traversaro
