{% set name = "yarp-device-realsense2" %}
{% set version = "0.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/robotology/yarp-device-realsense2/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5a2a4e169ef58a4214f0176bb6c7845c2726d5c49bcad98ffe12f75eeb535d20

build:
  number: 0
  # librealsense conda package is not available on Windows
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - librealsense
    - libyarp

test:
  commands:
    # Note: the devices are added in CMake add_library(... MODULE),
    # so also on macos they have the .so extension, instead of the .dylib
    # extension that add_library(... SHARED) typically have
    - test -f ${PREFIX}/lib/yarp/yarp_realsense2.so  # [not win]
    - test -f ${PREFIX}/lib/yarp/yarp_realsense2withIMU.so  # [not win]

about:
  home: https://github.com/robotology/yarp-device-realsense2
  license: BSD-3-Clause
  license_file: 
    - LICENSE
  summary: realsense2 device for YARP.

extra:
  feedstock-name: yarp-device-realsense2
  recipe-maintainers:
    - traversaro
